import { Cake } from './store';

export const cakes: Cake[] = [
  {
    id: '1',
    name: 'Classic Chocolate Dream',
    description: 'Rich, moist chocolate cake layered with velvety chocolate ganache and topped with chocolate shavings.',
    price: 45,
    category: 'Chocolate',
    flavor: 'Chocolate',
    occasion: 'Birthday',
    dietaryInfo: ['Vegetarian'],
    images: ['🍫', '🎂', '🍰'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 45 },
      { size: '8 inch (serves 12-16)', price: 65 },
      { size: '10 inch (serves 20-24)', price: 85 },
    ],
    frostingOptions: ['Chocolate Buttercream', 'Dark Chocolate Ganache', 'Milk Chocolate Frosting'],
    rating: 4.8,
    reviews: 127,
  },
  {
    id: '2',
    name: 'Vanilla Bean Elegance',
    description: 'Light and fluffy vanilla cake made with real vanilla beans, layered with smooth vanilla buttercream.',
    price: 42,
    category: 'Vanilla',
    flavor: 'Vanilla',
    occasion: 'Wedding',
    dietaryInfo: ['Vegetarian'],
    images: ['🎂', '💐', '✨'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 42 },
      { size: '8 inch (serves 12-16)', price: 60 },
      { size: '10 inch (serves 20-24)', price: 80 },
    ],
    frostingOptions: ['Vanilla Buttercream', 'Cream Cheese Frosting', 'Whipped Cream'],
    rating: 4.9,
    reviews: 203,
  },
  {
    id: '3',
    name: 'Red Velvet Romance',
    description: 'Luxurious red velvet cake with a hint of cocoa, paired with tangy cream cheese frosting.',
    price: 48,
    category: 'Red Velvet',
    flavor: 'Red Velvet',
    occasion: 'Anniversary',
    dietaryInfo: ['Vegetarian'],
    images: ['❤️', '🎂', '💝'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 48 },
      { size: '8 inch (serves 12-16)', price: 68 },
      { size: '10 inch (serves 20-24)', price: 90 },
    ],
    frostingOptions: ['Cream Cheese Frosting', 'Ermine Frosting', 'White Chocolate Cream'],
    rating: 4.7,
    reviews: 156,
  },
  {
    id: '4',
    name: 'Lemon Sunshine Delight',
    description: 'Zesty lemon cake with fresh lemon curd filling and light lemon buttercream frosting.',
    price: 46,
    category: 'Fruit',
    flavor: 'Lemon',
    occasion: 'Summer Party',
    dietaryInfo: ['Vegetarian'],
    images: ['🍋', '☀️', '🎂'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 46 },
      { size: '8 inch (serves 12-16)', price: 66 },
      { size: '10 inch (serves 20-24)', price: 86 },
    ],
    frostingOptions: ['Lemon Buttercream', 'Lemon Cream Cheese', 'Lemon Glaze'],
    rating: 4.6,
    reviews: 89,
  },
  {
    id: '5',
    name: 'Strawberry Fields',
    description: 'Fresh strawberry cake with strawberry compote and fluffy strawberry cream cheese frosting.',
    price: 50,
    category: 'Fruit',
    flavor: 'Strawberry',
    occasion: 'Birthday',
    dietaryInfo: ['Vegetarian'],
    images: ['🍓', '🎂', '💗'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 50 },
      { size: '8 inch (serves 12-16)', price: 70 },
      { size: '10 inch (serves 20-24)', price: 92 },
    ],
    frostingOptions: ['Strawberry Buttercream', 'Strawberry Cream Cheese', 'Whipped Strawberry'],
    rating: 4.8,
    reviews: 134,
  },
  {
    id: '6',
    name: 'Carrot Garden Cake',
    description: 'Spiced carrot cake loaded with walnuts and raisins, topped with cream cheese frosting.',
    price: 44,
    category: 'Specialty',
    flavor: 'Carrot',
    occasion: 'Any Occasion',
    dietaryInfo: ['Vegetarian', 'Contains Nuts'],
    images: ['🥕', '🎂', '🌿'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 44 },
      { size: '8 inch (serves 12-16)', price: 62 },
      { size: '10 inch (serves 20-24)', price: 82 },
    ],
    frostingOptions: ['Cream Cheese Frosting', 'Maple Cream Cheese', 'Spiced Buttercream'],
    rating: 4.7,
    reviews: 98,
  },
  {
    id: '7',
    name: 'Cookies & Cream Fantasy',
    description: 'Vanilla cake studded with cookie pieces, layered with cookies and cream buttercream.',
    price: 52,
    category: 'Specialty',
    flavor: 'Cookies & Cream',
    occasion: 'Birthday',
    dietaryInfo: ['Vegetarian'],
    images: ['🍪', '🎂', '🤍'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 52 },
      { size: '8 inch (serves 12-16)', price: 72 },
      { size: '10 inch (serves 20-24)', price: 95 },
    ],
    frostingOptions: ['Cookies & Cream Buttercream', 'Vanilla Buttercream', 'Cream Cheese Frosting'],
    rating: 4.9,
    reviews: 176,
  },
  {
    id: '8',
    name: 'Salted Caramel Heaven',
    description: 'Caramel-infused cake layers with salted caramel sauce and caramel buttercream frosting.',
    price: 55,
    category: 'Specialty',
    flavor: 'Caramel',
    occasion: 'Any Occasion',
    dietaryInfo: ['Vegetarian'],
    images: ['🍮', '🎂', '✨'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 55 },
      { size: '8 inch (serves 12-16)', price: 75 },
      { size: '10 inch (serves 20-24)', price: 98 },
    ],
    frostingOptions: ['Salted Caramel Buttercream', 'Caramel Cream Cheese', 'Dulce de Leche'],
    rating: 4.9,
    reviews: 145,
  },
  {
    id: '9',
    name: 'Vegan Chocolate Bliss',
    description: 'Decadent chocolate cake made without any animal products, topped with rich vegan chocolate frosting.',
    price: 48,
    category: 'Chocolate',
    flavor: 'Chocolate',
    occasion: 'Any Occasion',
    dietaryInfo: ['Vegan', 'Dairy-Free', 'Egg-Free'],
    images: ['🍫', '🌱', '🎂'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 48 },
      { size: '8 inch (serves 12-16)', price: 68 },
      { size: '10 inch (serves 20-24)', price: 88 },
    ],
    frostingOptions: ['Vegan Chocolate Buttercream', 'Vegan Ganache', 'Coconut Chocolate'],
    rating: 4.6,
    reviews: 67,
  },
  {
    id: '10',
    name: 'Gluten-Free Vanilla Joy',
    description: 'Light and airy gluten-free vanilla cake that tastes just like the traditional version.',
    price: 50,
    category: 'Vanilla',
    flavor: 'Vanilla',
    occasion: 'Any Occasion',
    dietaryInfo: ['Gluten-Free', 'Vegetarian'],
    images: ['🎂', '🌾', '✨'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 50 },
      { size: '8 inch (serves 12-16)', price: 70 },
      { size: '10 inch (serves 20-24)', price: 92 },
    ],
    frostingOptions: ['Vanilla Buttercream', 'Cream Cheese Frosting', 'Swiss Meringue'],
    rating: 4.5,
    reviews: 54,
  },
  {
    id: '11',
    name: 'Tiramisu Tower',
    description: 'Italian-inspired coffee-soaked cake with mascarpone cream and cocoa powder dusting.',
    price: 58,
    category: 'Specialty',
    flavor: 'Coffee',
    occasion: 'Adult Birthday',
    dietaryInfo: ['Vegetarian', 'Contains Alcohol'],
    images: ['☕', '🎂', '🇮🇹'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 58 },
      { size: '8 inch (serves 12-16)', price: 78 },
      { size: '10 inch (serves 20-24)', price: 100 },
    ],
    frostingOptions: ['Mascarpone Cream', 'Coffee Buttercream', 'Espresso Ganache'],
    rating: 4.8,
    reviews: 112,
  },
  {
    id: '12',
    name: 'Rainbow Celebration',
    description: 'Colorful layers of vanilla cake in rainbow colors, topped with vanilla buttercream and sprinkles.',
    price: 52,
    category: 'Specialty',
    flavor: 'Vanilla',
    occasion: 'Kids Birthday',
    dietaryInfo: ['Vegetarian'],
    images: ['🌈', '🎂', '🎉'],
    sizes: [
      { size: '6 inch (serves 6-8)', price: 52 },
      { size: '8 inch (serves 12-16)', price: 72 },
      { size: '10 inch (serves 20-24)', price: 95 },
    ],
    frostingOptions: ['Vanilla Buttercream', 'Rainbow Swirl', 'Whipped Cream'],
    rating: 4.9,
    reviews: 234,
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Sarah Johnson',
    rating: 5,
    comment: 'The chocolate dream cake for my daughter\'s birthday was absolutely perfect! Everyone asked where we got it. The taste was incredible and the presentation was stunning.',
    date: '2024-03-15',
    avatar: '👩',
  },
  {
    id: 2,
    name: 'Michael Chen',
    rating: 5,
    comment: 'Ordered a custom wedding cake and it exceeded all expectations. The team was professional, accommodating, and the cake was the centerpiece of our reception. Highly recommend!',
    date: '2024-03-10',
    avatar: '👨',
  },
  {
    id: 3,
    name: 'Emily Rodriguez',
    rating: 5,
    comment: 'As someone with dietary restrictions, finding a delicious gluten-free cake has been challenging. Sweet Delights nailed it! You couldn\'t even tell it was gluten-free.',
    date: '2024-03-08',
    avatar: '👩‍🦰',
  },
  {
    id: 4,
    name: 'David Thompson',
    rating: 4,
    comment: 'Great variety of flavors and the online ordering process was seamless. The red velvet cake was moist and flavorful. Will definitely order again!',
    date: '2024-03-05',
    avatar: '👨‍🦳',
  },
  {
    id: 5,
    name: 'Lisa Wang',
    rating: 5,
    comment: 'The attention to detail is remarkable. They created exactly what I envisioned for my son\'s graduation cake. Customer service was excellent throughout the process.',
    date: '2024-02-28',
    avatar: '👩‍💼',
  },
];
